// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: audit.sql

package pgstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_logs (user_id, email, action, ip, user_agent, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertAuditLogParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	Email     pgtype.Text `json:"email"`
	Action    string      `json:"action"`
	Ip        pgtype.Text `json:"ip"`
	UserAgent pgtype.Text `json:"user_agent"`
	Metadata  []byte      `json:"metadata"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.UserID,
		arg.Email,
		arg.Action,
		arg.Ip,
		arg.UserAgent,
		arg.Metadata,
	)
	return err
}
